
name: serialization_task
description: A task for serialization and deserialization.
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:

dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.11.3