
name: serialization_task
description: A task for serialization and deserialization.
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  toml: ^0.17.0
  json_annotation: ^4.9.0
  yaml_writer: 2.1.0

dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.11.3