name: task_2
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  analyzer: ^6.4.1
  source_gen: ^1.2.0
  build_runner: ^2.4.0
  build: ^2.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
