name: task_1
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  collection: ^1.18.0
  glob: ^2.1.2
  # path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.4
  lints: ^6.0.0
  test: ^1.25.6
